server:
  context-path: /ang-eureka
  port: 8043
eureka:
  instance:
    hostname: Server43
  client:
    service-url:
      defaultZone: http://Server41:8041/${server.context-path}/eureka/,http://Server42:8042/${server.context-path}/eureka/