server:
  context-path: /ang-eureka
  port: 8042
eureka:
  instance:
    hostname: Server42
  client:
    service-url:
      defaultZone: http://Server41:8041/${server.context-path}/eureka/,http://Server43:8043/${server.context-path}/eureka/